### ISSUE TITLE
background and gutter-fg being same makes linum invisible

### ISSUE THREAD

**Issue by ghost** [nickav/naysayer-theme.el#3]
Is it intended?

**Comment by nickav** [comment]
not intended, i don't personally use linum. just added [this commit](https://github.com/nickav/naysayer-theme.el/commit/8eed91b268403cb9043e0c9d9aaf324db1ab7d7e) yesterday to hopefully fix the issue

**Comment by nickav** [comment]
feel free to re-open if this is still an issue
